name: Build & Push to ECR

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }} ./app

      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push to ECR
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # ------------------------------------------------------------------
      # Trigger & Validate ECS Deployment
      # ------------------------------------------------------------------

      - name: Force new ECS deployment using latest image
        run: |
          aws ecs update-service \
            --cluster ecs-python-api-dev-cluster \
            --service ecs-python-api-dev-service \
            --force-new-deployment

      - name: Wait for ECS to stabilize
        run: |
          echo "Waiting for ECS service to stabilize..."
          aws ecs wait services-stable \
            --cluster ecs-python-api-dev-cluster \
            --services ecs-python-api-dev-service

      - name: Check ECS Deployment Status
        run: |
          STATUS=$(aws ecs describe-services \
            --cluster ecs-python-api-dev-cluster \
            --services ecs-python-api-dev-service \
            --query "services[0].deployments[?status=='PRIMARY'].rolloutState" \
            --output text)

          echo "Deployment Status: $STATUS"

          if [ "$STATUS" != "COMPLETED" ]; then
            echo "‚ùå ECS Deployment FAILED"
            exit 1
          fi

      - name: Deployment Successful
        if: success()
        run: echo "üöÄ Deployment is stable and tasks are healthy!"
